'use client';
import { useCallback,useEffect,useState,type FormEvent } from 'react';
import { Show,SignInButton,useAuth } from '@/components/auth/local-auth';
import Link from 'next/link';
import { MarketHeader,MarketFooter } from '@/components/market-header';
type Listing={id:number;title:string;origin:string;destination:string;offeredCents:number;status:string;selectedOfferId:number|null;hasReview:number;reviewNote:string|null};
type Profile={about:string;serviceArea:string;vehicleDetails:string;equipment:string;businessType:string;insuranceDescription:string;hasMc:boolean;hasDot:boolean;vehiclePhotoUrl:string|null;profilePhotoUrl:string|null;reviewCount:number;reviewAverage:number|null;reviews:{rating:number;comment:string;createdAt:string}[]};
type Offer={id:number;driverName:string;driverEmail:string|null;amountCents:number;note:string;status:string;profile:Profile|null};
export default function MyLoads(){
 const {isSignedIn}=useAuth();const [listings,setListings]=useState<Listing[]>([]),[offers,setOffers]=useState<Record<number,Offer[]>>({}),[fee,setFee]=useState(1900),[checkoutAvailable,setCheckoutAvailable]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState('');
 const [reviewFor,setReviewFor]=useState<number|null>(null),[rating,setRating]=useState(5),[comment,setComment]=useState(''),[completed,setCompleted]=useState(false),[reviewed,setReviewed]=useState<number[]>([]);
 const refresh=useCallback(async()=>{if(!isSignedIn)return;setBusy(true);try{
  const r=await fetch('/api/market/listings?mine=1');const d=await r.json() as {error?:string;listings?:Listing[];feeCents?:number;checkoutAvailable?:boolean};if(!r.ok)throw new Error(d.error);
  setListings(d.listings||[]);setFee(d.feeCents||1900);setCheckoutAvailable(Boolean(d.checkoutAvailable));
  const entries=await Promise.all((d.listings||[]).filter(l=>l.status==='open'||l.status==='selected').map(async l=>{const res=await fetch(`/api/market/listings/${l.id}/offers`);const body=await res.json() as {offers?:Offer[]};return [l.id,res.ok?(body.offers||[]):[]] as const}));setOffers(Object.fromEntries(entries));
 }catch(e){setError(e instanceof Error?e.message:'Could not load listings.')}finally{setBusy(false)}},[isSignedIn]);
 useEffect(()=>{const frame=requestAnimationFrame(()=>void refresh());return()=>cancelAnimationFrame(frame)},[refresh]);
 async function checkout(id:number){setBusy(true);setError('');try{const r=await fetch(`/api/market/listings/${id}/checkout`,{method:'POST'});const d=await r.json() as {error?:string;url?:string};if(!r.ok)throw new Error(d.error);if(d.url)window.location.assign(d.url)}catch(e){setError(e instanceof Error?e.message:'Checkout unavailable.')}finally{setBusy(false)}}
 async function select(id:number,offerId:number){if(!window.confirm('Select this driver? You will be able to contact each other to confirm final terms and payment.'))return;setBusy(true);setError('');try{const r=await fetch(`/api/market/listings/${id}/select`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({offerId})});const d=await r.json() as {error?:string};if(!r.ok)throw new Error(d.error);setMessage('Driver selected. Confirm the full job and payment directly before delivery.');await refresh()}catch(e){setError(e instanceof Error?e.message:'Selection failed.')}finally{setBusy(false)}}
 async function review(e:FormEvent,id:number){e.preventDefault();setBusy(true);setError('');try{const r=await fetch(`/api/market/listings/${id}/review`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({rating,comment,deliveryCompleted:completed})});const d=await r.json() as {error?:string};if(!r.ok)throw new Error(d.error);setReviewed(prev=>[...prev,id]);setReviewFor(null);setMessage('Your review was saved. Thank you for sharing how the delivery went.');await refresh()}catch(e){setError(e instanceof Error?e.message:'Could not save review.')}finally{setBusy(false)}}
 return <><MarketHeader/><main id="main-content" className="market-board-page"><div className="shell"><div className="market-page-heading"><span className="market-label">YOUR ACCOUNT</span><h1>MY LISTINGS.</h1><p>Publish a load, compare the drivers who respond, and select who to hire. Driver profiles are visible only here after they make an offer on your paid listing.</p><Link href="/post-load" className="primary">Post another load</Link></div>
 {error&&<p role="alert" className="notice error">{error}</p>}{message&&<p role="status" className="notice success">{message}</p>}
 <Show when="signed-out"><div className="market-empty"><h2>Sign in to see your listings.</h2><SignInButton mode="modal"><button className="primary">Sign in</button></SignInButton></div></Show>
 <Show when="signed-in"><div className="market-my-list"><button className="secondary" onClick={()=>void refresh()} disabled={busy}>Refresh listings</button>{!busy&&listings.length===0&&<div className="market-empty"><h2>No listings yet.</h2><p>Start with the route and a description of what needs to move.</p></div>}
 {listings.map(l=><article key={l.id} className="market-listing"><div className="market-listing-top"><span>LISTING #{l.id}</span><strong>{l.status==='review_pending'?'AWAITING AVL REVIEW':l.status==='review_declined'?'NEEDS CHANGES':l.status==='draft'?'DRAFT · PAYMENT NEEDED':l.status==='selected'?'DRIVER SELECTED':'OPEN FOR OFFERS'}</strong></div><h2>{l.title}</h2><p className="market-listing-route">{l.origin} → {l.destination}</p><p>Your starting offer: <strong>${(l.offeredCents/100).toLocaleString()}</strong></p>
 {l.status==='review_pending'&&<div className="market-draft-pay"><p>AVL is reviewing this test submission. It is not visible to drivers yet. No listing fee has been charged.</p></div>}{l.status==='review_declined'&&<div className="market-draft-pay"><p>AVL declined this submission: {l.reviewNote||'Please contact AVL for details.'}</p></div>}{l.status==='draft'&&<div className="market-draft-pay"><p>Pay the ${(fee/100).toFixed(2)} listing fee to publish. AVL does not collect delivery pay.</p>{checkoutAvailable?<button className="primary" disabled={busy} onClick={()=>void checkout(l.id)}>Pay listing fee and publish</button>:<p role="status"><strong>Checkout is being connected.</strong> Your draft is saved. Publication will be available here when setup is complete.</p>}</div>}
 {(l.status==='open'||l.status==='selected')&&<div className="market-offers"><h3>Driver offers ({(offers[l.id]||[]).length})</h3>{!(offers[l.id]||[]).length&&<p>No offers yet. Your listing is live on the board.</p>}
 {(offers[l.id]||[]).map(o=><div className="market-offer-row" key={o.id}><div className="market-offer-detail"><strong>{o.driverName} · ${(o.amountCents/100).toLocaleString()}</strong><p>{o.note}</p>{l.selectedOfferId===o.id&&o.driverEmail&&<p><strong>Contact:</strong> <a href={`mailto:${o.driverEmail}`}>{o.driverEmail}</a></p>}</div>
 {o.profile&&<div className="market-driver-profile"><div className="market-driver-photos">{o.profile.vehiclePhotoUrl&&<img src={o.profile.vehiclePhotoUrl} alt="Driver's vehicle"/>}{o.profile.profilePhotoUrl&&<img src={o.profile.profilePhotoUrl} alt="Driver's optional profile photo"/>}</div><div className="market-driver-facts"><p><strong>Equipment:</strong> {o.profile.equipment||'Not provided'}</p>{o.profile.vehicleDetails&&<p><strong>Vehicle:</strong> {o.profile.vehicleDetails}</p>}{o.profile.serviceArea&&<p><strong>Regular lanes:</strong> {o.profile.serviceArea}</p>}{o.profile.about&&<p><strong>About:</strong> {o.profile.about}</p>}<p><strong>Business:</strong> {o.profile.businessType?.replaceAll('_',' ')||'Not specified'} · {o.profile.hasMc?'MC number provided':'No MC number provided'}{o.profile.hasDot?' · USDOT provided':''}</p><p><strong>Insurance:</strong> {o.profile.insuranceDescription||'No insurance details supplied'} <small>(self-reported; confirm credentials directly)</small></p><p><strong>AVL shipper feedback:</strong> {o.profile.reviewCount?`${o.profile.reviewAverage}/5 from ${o.profile.reviewCount} ${o.profile.reviewCount===1?'review':'reviews'}`:'No reviews yet'}</p>{o.profile.reviews.map((r,index)=><blockquote key={index}>“{r.comment}” <span>· {r.rating}/5</span></blockquote>)}</div></div>}
 {l.status==='open'&&<button className="secondary" disabled={busy} onClick={()=>void select(l.id,o.id)}>Select driver</button>}{o.status==='selected'&&<span>Selected</span>}</div>)}</div>}
 {l.status==='selected'&&<div className="market-review-block"><p className="market-privacy">You and the selected driver now have each other’s contact information. Confirm addresses, responsibilities, timing, authority, and payment directly. AVL’s listing fee does not cover delivery.</p>{!l.hasReview&&!reviewed.includes(l.id)&&<button className="secondary" onClick={()=>setReviewFor(reviewFor===l.id?null:l.id)}>{reviewFor===l.id?'Close':'Review this driver after delivery'}</button>}{Boolean(l.hasReview)&&<p className="market-privacy">Your review is on file. Thank you.</p>}{reviewFor===l.id&&<form onSubmit={e=>void review(e,l.id)}><label>Rating<select value={rating} onChange={e=>setRating(Number(e.target.value))}>{[5,4,3,2,1].map(n=><option key={n} value={n}>{n} out of 5</option>)}</select></label><label>How did the delivery go?<textarea required minLength={20} maxLength={700} value={comment} onChange={e=>setComment(e.target.value)} placeholder="Describe communication, handling, and reliability. Do not include contact details."/></label><label className="market-check"><input type="checkbox" checked={completed} onChange={e=>setCompleted(e.target.checked)} required/> I confirm the delivery was completed.</label><button className="primary" disabled={busy}>Submit review</button></form>}</div>}
 </article>)}</div></Show></div></main><MarketFooter/></>}
