'use client';
import { useCallback,useEffect,useState } from 'react';
import { Show, SignInButton, useAuth } from '@clerk/nextjs';
import Link from 'next/link';
import { MarketHeader, MarketFooter } from '@/components/market-header';
type Listing={id:number;title:string;origin:string;destination:string;offeredCents:number;status:string;selectedOfferId:number|null};
type Offer={id:number;driverName:string;driverEmail:string|null;amountCents:number;note:string;status:string};
export default function MyLoads(){const {isSignedIn}=useAuth();const [listings,setListings]=useState<Listing[]>([]),[offers,setOffers]=useState<Record<number,Offer[]>>({}),[fee,setFee]=useState(1900),[checkoutAvailable,setCheckoutAvailable]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState('');
 const refresh=useCallback(async()=>{if(!isSignedIn)return;setBusy(true);try{const r=await fetch('/api/market/listings?mine=1');const d=await r.json() as {error?:string;listings?:Listing[];feeCents?:number;checkoutAvailable?:boolean};if(!r.ok)throw new Error(d.error);setListings(d.listings||[]);setFee(d.feeCents||1900);setCheckoutAvailable(Boolean(d.checkoutAvailable));const entries=await Promise.all((d.listings||[]).filter((l:Listing)=>l.status==='open'||l.status==='selected').map(async(l:Listing)=>{const res=await fetch(`/api/market/listings/${l.id}/offers`);const body=await res.json() as {offers?:Offer[]};return [l.id,res.ok?(body.offers||[]):[]] as const}));setOffers(Object.fromEntries(entries))}catch(e){setError(e instanceof Error?e.message:'Could not load listings.')}finally{setBusy(false)}},[isSignedIn]);
 useEffect(()=>{const frame=requestAnimationFrame(()=>void refresh());return()=>cancelAnimationFrame(frame)},[refresh]);
 async function checkout(id:number){setBusy(true);setError('');try{const r=await fetch(`/api/market/listings/${id}/checkout`,{method:'POST'});const d=await r.json() as {error?:string;url?:string};if(!r.ok)throw new Error(d.error);if(d.url)window.location.assign(d.url)}catch(e){setError(e instanceof Error?e.message:'Checkout unavailable.')}finally{setBusy(false)}}
 async function select(id:number,offerId:number){if(!window.confirm('Select this driver? You will be able to contact each other to confirm the final delivery terms and payment.'))return;setBusy(true);setError('');try{const r=await fetch(`/api/market/listings/${id}/select`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({offerId})});const d=await r.json() as {error?:string};if(!r.ok)throw new Error(d.error);setMessage('Driver selected. Confirm the exact scope, addresses, and payment directly before delivery.');await refresh()}catch(e){setError(e instanceof Error?e.message:'Selection failed.')}finally{setBusy(false)}}
 return <><MarketHeader/><main id="main-content" className="market-board-page"><div className="shell"><div className="market-page-heading"><span className="market-label">YOUR ACCOUNT</span><h1>MY LISTINGS.</h1><p>Pay to publish a draft, review driver offers, and select the person you want to hire. The delivery payment is arranged directly with the driver.</p><Link href="/post-load" className="primary">Post another load</Link></div>{error&&<p role="alert" className="notice error">{error}</p>}{message&&<p role="status" className="notice success">{message}</p>}<Show when="signed-out"><div className="market-empty"><h2>Sign in to see your listings.</h2><SignInButton mode="modal"><button className="primary">Sign in</button></SignInButton></div></Show><Show when="signed-in"><div className="market-my-list"><button className="secondary" onClick={()=>void refresh()} disabled={busy}>Refresh listings</button>{!busy&&listings.length===0&&<div className="market-empty"><h2>No listings yet.</h2><p>Start with the route and a description of what needs to move.</p></div>}{listings.map(l=><article key={l.id} className="market-listing"><div className="market-listing-top"><span>LISTING #{l.id}</span><strong>{l.status==='draft'?'DRAFT · PAYMENT NEEDED':l.status==='selected'?'DRIVER SELECTED':'OPEN FOR OFFERS'}</strong></div><h2>{l.title}</h2><p className="market-listing-route">{l.origin} → {l.destination}</p><p>Your starting offer: <strong>${(l.offeredCents/100).toLocaleString()}</strong></p>{l.status==='draft'&&<div className="market-draft-pay"><p>Pay the ${ (fee/100).toFixed(2) } listing fee to publish. No driver is charged, and AVL does not process delivery pay.</p>{checkoutAvailable?<button className="primary" disabled={busy} onClick={()=>void checkout(l.id)}>Pay listing fee and publish</button>:<p role="status"><strong>Checkout is being connected.</strong> Your draft is saved. Payment and publication will be available here when setup is complete.</p>}</div>}{(l.status==='open'||l.status==='selected')&&<div className="market-offers"><h3>Driver offers ({(offers[l.id]||[]).length})</h3>{!(offers[l.id]||[]).length&&<p>No offers yet. Your listing is live on the board.</p>}{(offers[l.id]||[]).map(o=><div className="market-offer-row" key={o.id}><div><strong>{o.driverName} · ${(o.amountCents/100).toLocaleString()}</strong><p>{o.note}</p>{l.selectedOfferId===o.id&&o.driverEmail&&<p><strong>Contact:</strong> <a href={`mailto:${o.driverEmail}`}>{o.driverEmail}</a></p>}</div>{l.status==='open'&&<button className="secondary" disabled={busy} onClick={()=>void select(l.id,o.id)}>Select driver</button>}{o.status==='selected'&&<span>Selected</span>}</div>)}</div>}{l.status==='selected'&&<p className="market-privacy">You and the selected driver now have each other’s contact information. Confirm addresses, responsibilities, timing, and payment directly. AVL’s listing fee does not cover the delivery.</p>}</article>)}</div></Show></div></main><MarketFooter/></>}
