import { env } from 'cloudflare:workers';
import { isOperator } from '@/lib/operator';
import { NextResponse } from 'next/server';
import { z } from 'zod';
export const dynamic='force-dynamic';
export async function GET(){if(!await isOperator())return NextResponse.json({error:'Access restricted to the review team.'},{status:403});try{const [loads,bids]=await Promise.all([env.DB!.prepare('SELECT id,title,category,description,origin,destination,pickup_date AS pickupDate,public_origin AS publicOrigin,public_destination AS publicDestination,public_summary AS publicSummary,pickup_type AS pickupType,carry_help AS carryHelp,contact_name AS contactName,contact_email AS contactEmail,contact_phone AS contactPhone,contact_preference AS contactPreference,listing_url AS listingUrl,status,quote_cents AS quoteCents,quote_note AS quoteNote,quote_source AS quoteSource FROM loads ORDER BY id DESC LIMIT 100').all(),env.DB!.prepare('SELECT id,load_id AS loadId,carrier_name AS carrierName,contact_email AS contactEmail,mc_number AS mcNumber,equipment,amount,note,status FROM bids ORDER BY id DESC LIMIT 100').all()]);return NextResponse.json({loads:loads.results,bids:bids.results})}catch(e){console.error('Review fetch failed',e);return NextResponse.json({error:'Review workspace unavailable.'},{status:503})}}
const updateSchema=z.discriminatedUnion('action',[
  z.object({action:z.literal('status'),id:z.number().int().positive(),status:z.enum(['broker_review','open','closed']),publicOrigin:z.string().trim().min(2).max(100).optional(),publicDestination:z.string().trim().min(2).max(100).optional(),publicSummary:z.string().trim().min(10).max(500).optional()}),
  z.object({action:z.literal('quote'),id:z.number().int().positive(),quoteCents:z.number().int().min(100).max(100000000),quoteSource:z.enum(['AVL local delivery','Roadie','Curri','Warp','Participating carrier','Other']),quoteNote:z.string().trim().min(10).max(1000)}),
  z.object({action:z.literal('unable'),id:z.number().int().positive(),quoteNote:z.string().trim().min(10).max(1000)}),
]);
export async function PATCH(req:Request){if(!await isOperator())return NextResponse.json({error:'Access restricted to the review team.'},{status:403});const parsed=updateSchema.safeParse(await req.json().catch(()=>null));if(!parsed.success)return NextResponse.json({error:'Check the quote or status details.'},{status:400});const d=parsed.data;try{const load=await env.DB!.prepare('SELECT id,status,current_quote_id,estimate_id FROM loads WHERE id=?').bind(d.id).first<{id:number;status:string;current_quote_id:string|null;estimate_id:string|null}>();if(!load)return NextResponse.json({error:'Request not found.'},{status:404});if(load.current_quote_id||load.estimate_id)return NextResponse.json({error:'Manage this request in the quote desk.'},{status:409});if(d.action==='quote'){if(load.status==='closed')return NextResponse.json({error:'Closed requests cannot be quoted.'},{status:409});await env.DB!.prepare("UPDATE loads SET status='quote_ready',quote_cents=?,quote_source=?,quote_note=?,quoted_at=? WHERE id=?").bind(d.quoteCents,d.quoteSource,d.quoteNote,new Date().toISOString(),d.id).run()}else if(d.action==='unable'){await env.DB!.prepare("UPDATE loads SET status='unable_to_quote',quote_cents=NULL,quote_source=NULL,quote_note=?,quoted_at=? WHERE id=?").bind(d.quoteNote,new Date().toISOString(),d.id).run()}else{if(d.status==='open'){if(!d.publicOrigin||!d.publicDestination||!d.publicSummary)return NextResponse.json({error:'Add town-level locations and a public load summary before opening the board.'},{status:400});await env.DB!.prepare('UPDATE loads SET status=?,public_origin=?,public_destination=?,public_summary=? WHERE id=?').bind(d.status,d.publicOrigin,d.publicDestination,d.publicSummary,d.id).run()}else{await env.DB!.prepare('UPDATE loads SET status=? WHERE id=?').bind(d.status,d.id).run()}}return NextResponse.json({ok:true})}catch(e){console.error('Review update failed',e);return NextResponse.json({error:'Could not update the request.'},{status:503})}}
